# Generated by Django 5.1.7 on 2025-03-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('To-Do', 'To-Do'), ('In-Progress', 'In-Progress'), ('Review', 'Review'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='To-Do', max_length=20),
        ),
    ]
